# Generated by Django 5.0 on 2023-12-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invention',
            name='lastname',
        ),
    ]
