# Generated by Django 5.0 on 2023-12-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_code_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='invention',
            name='product_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invention',
            name='supplier_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
